/**
 * Transform Contact from Agendor to ZafChat
 * 
 * Agendor: People + Organizations
 * ZafChat: contactCrm
 */

const logger = require('../lib/logger');

/**
 * Normalize phone number
 * Priority: whatsapp > mobile > work
 */
function normalizePhone(contact, fallbackId) {
  if (!contact) {
    return {
      number: `AGENDOR-${fallbackId}`,
      status: 'imported_without_phone',
      valid: false,
      source: null
    };
  }

  const phone = contact.whatsapp || contact.mobile || contact.work;
  
  if (!phone) {
    return {
      number: `AGENDOR-${fallbackId}`,
      status: 'imported_without_phone',
      valid: false,
      source: null
    };
  }

  let normalized = phone
    .replace(/\D/g, '')
    .replace(/^0+/, '');

  // Add country code if needed (Brazil = 55)
  if (normalized.length === 10 || normalized.length === 11) {
    normalized = '55' + normalized;
  }

  const isValid = normalized.length >= 12 && normalized.length <= 15;

  return {
    number: isValid ? normalized : `AGENDOR-${fallbackId}`,
    status: isValid ? 'open' : 'imported_without_phone',
    valid: isValid,
    originalPhone: phone,
    source: contact.whatsapp ? 'whatsapp' : contact.mobile ? 'mobile' : 'work'
  };
}

/**
 * Transform Agendor Person to ZafChat Contact
 */
function transformPerson(agendorPerson, mappings, config) {
  const phoneData = normalizePhone(agendorPerson.contact, agendorPerson.id);
  
  const responsibleUserId = mappings.users[agendorPerson.ownerUser?.id] || config.DEFAULT_USER_ID;

  return {
    // Key fields
    number: phoneData.number,
    
    // Contact info
    name: agendorPerson.name || 'Sem nome',
    contactId: null, // Will be generated by ZafChat
    
    // Assignment
    responsibleUserId: responsibleUserId,
    assignedSector: null,
    assignedBy: null,
    assignedAt: null,
    
    // Status
    status: phoneData.status,
    active: true,
    priority: 'normal',
    
    // Organization
    organizationId: null,
    organizationName: agendorPerson.organization?.name || null,
    
    // Metadata
    projectId: config.PROJECT_ID,
    tags: [],
    notes: null,
    noteHistory: [],
    
    // Location (not available in Agendor)
    city: null,
    state: null,
    address: null,
    zipCode: null,
    origin: agendorPerson.leadOrigin?.name || 'Agendor Migration',
    source: 'agendor',
    
    // Flags
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    isSpam: false,
    
    // Timestamps
    lastInteraction: agendorPerson.updatedAt ? new Date(agendorPerson.updatedAt) : new Date(),
    createdAt: agendorPerson.createdAt ? new Date(agendorPerson.createdAt) : new Date(),
    updatedAt: new Date(),
    
    // Migration metadata
    _agendorId: agendorPerson.id,
    _agendorEmail: agendorPerson.email || agendorPerson.contact?.email,
    _phoneValid: phoneData.valid,
    _phoneOriginal: phoneData.originalPhone,
    _phoneSource: phoneData.source
  };
}

/**
 * Transform Agendor Organization to ZafChat Contact
 */
function transformOrganization(agendorOrg, mappings, config) {
  const phoneData = normalizePhone(agendorOrg.contact, agendorOrg.id);
  
  const responsibleUserId = mappings.users[agendorOrg.ownerUser?.id] || config.DEFAULT_USER_ID;

  return {
    // Key fields
    number: phoneData.number,
    
    // Contact info (using organization name)
    name: agendorOrg.name || agendorOrg.legalName || 'Sem nome',
    contactId: null,
    
    // Assignment
    responsibleUserId: responsibleUserId,
    assignedSector: null,
    assignedBy: null,
    assignedAt: null,
    
    // Status
    status: phoneData.status,
    active: true,
    priority: 'normal',
    
    // Organization (self-reference)
    organizationId: null,
    organizationName: agendorOrg.legalName || agendorOrg.name,
    
    // Metadata
    projectId: config.PROJECT_ID,
    tags: [],
    notes: agendorOrg.description || null,
    noteHistory: [],
    
    // Location
    city: agendorOrg.address?.city || null,
    state: agendorOrg.address?.state || null,
    address: agendorOrg.address?.street || null,
    zipCode: agendorOrg.address?.postalCode || null,
    origin: agendorOrg.leadOrigin?.name || 'Agendor Migration',
    source: 'agendor',
    
    // Flags
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    isSpam: false,
    
    // Timestamps
    lastInteraction: agendorOrg.updatedAt ? new Date(agendorOrg.updatedAt) : new Date(),
    createdAt: agendorOrg.createdAt ? new Date(agendorOrg.createdAt) : new Date(),
    updatedAt: new Date(),
    
    // Migration metadata
    _agendorId: agendorOrg.id,
    _agendorCNPJ: agendorOrg.cnpj,
    _agendorEmail: agendorOrg.email || agendorOrg.contact?.email,
    _phoneValid: phoneData.valid,
    _phoneOriginal: phoneData.originalPhone,
    _phoneSource: phoneData.source,
    _isOrganization: true
  };
}

module.exports = {
  normalizePhone,
  transformPerson,
  transformOrganization
};
